---
name: Release
on:
  push:
    tags:
      - v*
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build TypeScript
        run: npm run build
      - name: Package application
        run: npx pkg . --targets node18-linux-x64,node18-macos-x64,node18-win-x64
          --output dist/weathery
      - name: Prepare Release Assets
        run: |
          # For Linux
          mv dist/weathery-linux dist/weathery
          tar -czvf dist/weathery-linux-x64.tar.gz -C dist weathery
          rm dist/weathery

          # For macOS
          mv dist/weathery-macos dist/weathery
          tar -czvf dist/weathery-macos-x64.tar.gz -C dist weathery
          rm dist/weathery

          # For Windows
          mv dist/weathery-win.exe dist/weathery.exe
          zip -j dist/weathery-windows-x64.zip dist/weathery.exe
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/weathery-linux-x64.tar.gz
            dist/weathery-macos-x64.tar.gz
            dist/weathery-windows-x64.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}